/**
 * Fixed labels for the generated plan document.
 *
 * The LLM writes the *content* in the chosen language; these are the headings and table
 * labels around it, which are template text rather than model output. Keeping both in the
 * same language is the difference between a readable document and a bilingual mess.
 */
import type { AnalysisLanguage } from "@shared/languages";

export interface PlanStrings {
  title: (keyword: string) => string;
  generatedOn: string;
  generatedBy: string;
  sections: {
    overview: string;
    keywords: string;
    openSource: string;
    models: string;
    papers: string;
    features: string;
    stack: string;
    screens: string;
    phases: string;
    risks: string;
    community: string;
    similar: string;
    attachments: string;
  };
  difficulty: string;
  difficultyLevels: Record<"초급" | "중급" | "고급" | "전문가", string>;
  labels: {
    mainKeyword: string;
    collectedFrom: string;
    totalSources: string;
    area: string;
    technology: string;
    coreTech: string;
    designGuidelines: string;
    riskItems: string;
    licenseNotes: string;
    mitigation: string;
    stars: string;
    language: string;
    license: string;
    downloads: string;
    likes: string;
    hasCode: string;
    yes: string;
    no: string;
    points: string;
    comments: string;
    referenceDocs: string;
    referenceImages: string;
    referenceProjects: string;
    path: string;
    fileCount: string;
    directoryTree: string;
    partiallyScanned: string;
    characters: string;
    reflectedInDesign: string;
    attachmentsNote: string;
    projectsNote: string;
    screensNote: string;
    footer: string;
  };
  empty: {
    models: string;
    papers: string;
    community: string;
    similar: string;
    noDescription: string;
    defaultLicenseNote: string;
  };
  defaultScreens: string[];
}

const en: PlanStrings = {
  title: (k) => `App Development Plan: ${k}`,
  generatedOn: "Generated",
  generatedBy: "Automatically generated by BuildPlanner from multi-source research.",
  sections: {
    overview: "Overview",
    keywords: "Research Keywords",
    openSource: "Reference Open Source",
    models: "Reference AI Models",
    papers: "Related Papers",
    features: "Core Features",
    stack: "Tech Stack",
    screens: "Screen Structure",
    phases: "Development Phases",
    risks: "Risks and Licensing",
    community: "Community Reaction (Hacker News)",
    similar: "Similar Services",
    attachments: "Attached Reference Material",
  },
  difficulty: "Implementation Difficulty",
  difficultyLevels: { 초급: "Beginner", 중급: "Intermediate", 고급: "Advanced", 전문가: "Expert" },
  labels: {
    mainKeyword: "Primary keyword",
    collectedFrom: "Sources collected",
    totalSources: "Total sources",
    area: "Area",
    technology: "Technology",
    coreTech: "Core technologies",
    designGuidelines: "Design Guidelines (from reference images)",
    riskItems: "Risks",
    licenseNotes: "Licensing notes",
    mitigation: "Mitigation",
    stars: "Stars",
    language: "Language",
    license: "License",
    downloads: "Downloads",
    likes: "Likes",
    hasCode: "Code available",
    yes: "Yes",
    no: "No",
    points: "Points",
    comments: "Comments",
    referenceDocs: "Reference documents (.md)",
    referenceImages: "Reference images (interface/design)",
    referenceProjects: "Referenced local projects",
    path: "Path",
    fileCount: "Files",
    directoryTree: "Directory structure",
    partiallyScanned: "partially scanned",
    characters: "characters",
    reflectedInDesign: "reflected in the design guidelines",
    attachmentsNote:
      "Material supplied by the user. The plan above was written giving this material priority.",
    projectsNote: "This plan assumes it continues from the existing codebases below.",
    screensNote: "Recommended screen structure based on the analysis.",
    footer:
      "This plan was generated automatically by BuildPlanner. Review and adjust it before starting development.",
  },
  empty: {
    models: "_No related AI models were found._",
    papers: "_No related papers were found._",
    community: "_No related Hacker News discussion was found._",
    similar: "_No similar services were identified._",
    noDescription: "No description",
    defaultLicenseNote:
      "- Check the license of each collected open-source project individually.\n- MIT and Apache 2.0 permit commercial use; GPL requires releasing your source.",
  },
  defaultScreens: [
    "**Main screen** — enter a keyword and start research",
    "**Results screen** — collected sources by tab (GitHub / HF / Papers / HN)",
    "**Analysis screen** — AI analysis and key insights",
    "**Plan screen** — Markdown preview and download",
    "**History screen** — past research and plans",
  ],
};

const ko: PlanStrings = {
  title: (k) => `앱 개발 계획서: ${k}`,
  generatedOn: "생성일",
  generatedBy: "BuildPlanner로 자동 생성된 리서치 기반 개발 계획서입니다.",
  sections: {
    overview: "아이디어 개요",
    keywords: "조사 키워드",
    openSource: "참고 오픈소스",
    models: "참고 AI 모델",
    papers: "관련 논문/기술",
    features: "핵심 기능",
    stack: "기술 스택",
    screens: "화면 구성",
    phases: "개발 단계",
    risks: "리스크와 라이선스 검토",
    community: "커뮤니티 반응 (Hacker News)",
    similar: "유사 서비스",
    attachments: "첨부 참고 자료",
  },
  difficulty: "구현 난이도",
  difficultyLevels: { 초급: "초급", 중급: "중급", 고급: "고급", 전문가: "전문가" },
  labels: {
    mainKeyword: "주요 키워드",
    collectedFrom: "수집 소스",
    totalSources: "총 수집 소스",
    area: "영역",
    technology: "기술",
    coreTech: "핵심 기술",
    designGuidelines: "디자인 지침 (첨부 이미지 기반)",
    riskItems: "리스크 항목",
    licenseNotes: "라이선스 주의사항",
    mitigation: "대응 방안",
    stars: "Stars",
    language: "언어",
    license: "라이선스",
    downloads: "다운로드",
    likes: "좋아요",
    hasCode: "코드 유무",
    yes: "있음",
    no: "없음",
    points: "포인트",
    comments: "댓글",
    referenceDocs: "참고 문서 (.md)",
    referenceImages: "참고 이미지 (인터페이스/디자인)",
    referenceProjects: "참고 로컬 프로젝트",
    path: "경로",
    fileCount: "파일",
    directoryTree: "디렉터리 구조",
    partiallyScanned: "일부만 스캔됨",
    characters: "자",
    reflectedInDesign: "디자인 지침에 반영됨",
    attachmentsNote: "사용자가 직접 첨부한 자료이며, 위 계획은 이 자료를 우선 반영해 작성되었습니다.",
    projectsNote: "이 계획은 아래 기존 코드베이스를 이어받는 것을 전제로 작성되었습니다.",
    screensNote: "LLM 분석 기반 추천 화면 구성입니다.",
    footer:
      "이 계획서는 BuildPlanner에 의해 자동 생성되었습니다. 실제 개발 시 추가적인 검토와 조정이 필요합니다.",
  },
  empty: {
    models: "_관련 AI 모델을 찾지 못했습니다._",
    papers: "_관련 논문을 찾지 못했습니다._",
    community: "_관련 HN 토론을 찾지 못했습니다._",
    similar: "_유사 서비스 정보를 분석하지 못했습니다._",
    noDescription: "설명 없음",
    defaultLicenseNote:
      "- 수집된 오픈소스의 라이선스를 개별적으로 확인하세요.\n- MIT, Apache 2.0은 상업적 사용 가능하나, GPL은 소스코드 공개 의무가 있습니다.",
  },
  defaultScreens: [
    "**메인 화면** — 키워드 입력 및 리서치 시작",
    "**리서치 결과 화면** — 수집된 소스 탭별 표시 (GitHub / HF / Papers / HN)",
    "**분석 요약 화면** — LLM 분석 결과 및 핵심 인사이트",
    "**계획서 화면** — Markdown 계획서 미리보기 및 다운로드",
    "**히스토리 화면** — 과거 리서치 목록 및 계획서 조회",
  ],
};

const ja: PlanStrings = {
  ...en,
  title: (k) => `アプリ開発計画書: ${k}`,
  generatedOn: "作成日",
  generatedBy: "BuildPlanner がマルチソースリサーチから自動生成した開発計画書です。",
  sections: {
    overview: "アイデア概要",
    keywords: "調査キーワード",
    openSource: "参考オープンソース",
    models: "参考 AI モデル",
    papers: "関連論文",
    features: "コア機能",
    stack: "技術スタック",
    screens: "画面構成",
    phases: "開発フェーズ",
    risks: "リスクとライセンス",
    community: "コミュニティの反応 (Hacker News)",
    similar: "類似サービス",
    attachments: "添付参考資料",
  },
  difficulty: "実装難易度",
  difficultyLevels: { 초급: "初級", 중급: "中級", 고급: "上級", 전문가: "エキスパート" },
  labels: {
    ...en.labels,
    mainKeyword: "主要キーワード",
    collectedFrom: "収集ソース",
    totalSources: "総ソース数",
    area: "領域",
    technology: "技術",
    coreTech: "コア技術",
    designGuidelines: "デザイン指針 (添付画像に基づく)",
    riskItems: "リスク項目",
    licenseNotes: "ライセンス注意事項",
    mitigation: "対応策",
    language: "言語",
    license: "ライセンス",
    downloads: "ダウンロード",
    likes: "いいね",
    hasCode: "コードの有無",
    yes: "あり",
    no: "なし",
    points: "ポイント",
    comments: "コメント",
    referenceDocs: "参考ドキュメント (.md)",
    referenceImages: "参考画像 (インターフェース/デザイン)",
    referenceProjects: "参照ローカルプロジェクト",
    path: "パス",
    fileCount: "ファイル",
    directoryTree: "ディレクトリ構造",
    characters: "文字",
    screensNote: "分析に基づく推奨画面構成です。",
    footer:
      "この計画書は BuildPlanner によって自動生成されました。開発前に内容を確認・調整してください。",
  },
};

const zh: PlanStrings = {
  ...en,
  title: (k) => `应用开发计划书: ${k}`,
  generatedOn: "生成日期",
  generatedBy: "由 BuildPlanner 基于多源调研自动生成的开发计划书。",
  sections: {
    overview: "创意概述",
    keywords: "调研关键词",
    openSource: "参考开源项目",
    models: "参考 AI 模型",
    papers: "相关论文",
    features: "核心功能",
    stack: "技术栈",
    screens: "界面结构",
    phases: "开发阶段",
    risks: "风险与许可证",
    community: "社区反馈 (Hacker News)",
    similar: "同类服务",
    attachments: "附件参考资料",
  },
  difficulty: "实现难度",
  difficultyLevels: { 초급: "入门", 중급: "中级", 고급: "高级", 전문가: "专家" },
  labels: {
    ...en.labels,
    mainKeyword: "主要关键词",
    collectedFrom: "采集来源",
    totalSources: "来源总数",
    area: "领域",
    technology: "技术",
    coreTech: "核心技术",
    designGuidelines: "设计规范 (基于附件图片)",
    riskItems: "风险项",
    licenseNotes: "许可证注意事项",
    mitigation: "应对方案",
    language: "语言",
    license: "许可证",
    downloads: "下载量",
    likes: "点赞",
    hasCode: "是否有代码",
    yes: "有",
    no: "无",
    points: "积分",
    comments: "评论",
    referenceDocs: "参考文档 (.md)",
    referenceImages: "参考图片 (界面/设计)",
    referenceProjects: "引用的本地项目",
    path: "路径",
    fileCount: "文件",
    directoryTree: "目录结构",
    characters: "字",
    screensNote: "基于分析的推荐界面结构。",
    footer: "本计划书由 BuildPlanner 自动生成，开发前请复核并调整。",
  },
};

const fr: PlanStrings = {
  ...en,
  title: (k) => `Plan de développement : ${k}`,
  generatedOn: "Généré le",
  generatedBy: "Plan généré automatiquement par BuildPlanner à partir d'une recherche multi-sources.",
  sections: {
    overview: "Vue d'ensemble",
    keywords: "Mots-clés de recherche",
    openSource: "Projets open source de référence",
    models: "Modèles d'IA de référence",
    papers: "Articles scientifiques",
    features: "Fonctionnalités principales",
    stack: "Stack technique",
    screens: "Structure des écrans",
    phases: "Phases de développement",
    risks: "Risques et licences",
    community: "Réactions de la communauté (Hacker News)",
    similar: "Services similaires",
    attachments: "Documents de référence joints",
  },
  difficulty: "Difficulté de mise en œuvre",
  difficultyLevels: { 초급: "Débutant", 중급: "Intermédiaire", 고급: "Avancé", 전문가: "Expert" },
  labels: {
    ...en.labels,
    mainKeyword: "Mot-clé principal",
    collectedFrom: "Sources collectées",
    totalSources: "Total des sources",
    area: "Domaine",
    technology: "Technologie",
    coreTech: "Technologies clés",
    designGuidelines: "Directives de design (d'après les images jointes)",
    riskItems: "Risques",
    licenseNotes: "Remarques sur les licences",
    mitigation: "Mesure d'atténuation",
    language: "Langage",
    license: "Licence",
    downloads: "Téléchargements",
    likes: "J'aime",
    hasCode: "Code disponible",
    yes: "Oui",
    no: "Non",
    points: "Points",
    comments: "Commentaires",
    referenceDocs: "Documents de référence (.md)",
    referenceImages: "Images de référence (interface/design)",
    referenceProjects: "Projets locaux référencés",
    path: "Chemin",
    fileCount: "Fichiers",
    directoryTree: "Arborescence",
    characters: "caractères",
    screensNote: "Structure d'écrans recommandée d'après l'analyse.",
    footer:
      "Ce plan a été généré automatiquement par BuildPlanner. Relisez-le et ajustez-le avant de démarrer.",
  },
};

const ru: PlanStrings = {
  ...en,
  title: (k) => `План разработки приложения: ${k}`,
  generatedOn: "Создано",
  generatedBy: "План автоматически сформирован BuildPlanner на основе исследования нескольких источников.",
  sections: {
    overview: "Обзор идеи",
    keywords: "Ключевые слова исследования",
    openSource: "Опорные open source проекты",
    models: "Опорные модели ИИ",
    papers: "Связанные статьи",
    features: "Ключевые возможности",
    stack: "Технологический стек",
    screens: "Структура экранов",
    phases: "Этапы разработки",
    risks: "Риски и лицензии",
    community: "Реакция сообщества (Hacker News)",
    similar: "Похожие сервисы",
    attachments: "Приложенные материалы",
  },
  difficulty: "Сложность реализации",
  difficultyLevels: { 초급: "Начальный", 중급: "Средний", 고급: "Продвинутый", 전문가: "Экспертный" },
  labels: {
    ...en.labels,
    mainKeyword: "Основное ключевое слово",
    collectedFrom: "Собранные источники",
    totalSources: "Всего источников",
    area: "Область",
    technology: "Технология",
    coreTech: "Ключевые технологии",
    designGuidelines: "Рекомендации по дизайну (по приложенным изображениям)",
    riskItems: "Риски",
    licenseNotes: "Замечания по лицензиям",
    mitigation: "Меры",
    language: "Язык",
    license: "Лицензия",
    downloads: "Загрузки",
    likes: "Лайки",
    hasCode: "Есть код",
    yes: "Да",
    no: "Нет",
    points: "Очки",
    comments: "Комментарии",
    referenceDocs: "Справочные документы (.md)",
    referenceImages: "Справочные изображения (интерфейс/дизайн)",
    referenceProjects: "Указанные локальные проекты",
    path: "Путь",
    fileCount: "Файлов",
    directoryTree: "Структура каталогов",
    characters: "символов",
    screensNote: "Рекомендуемая структура экранов по итогам анализа.",
    footer:
      "Этот план сформирован BuildPlanner автоматически. Проверьте и скорректируйте его перед началом разработки.",
  },
};

const STRINGS: Record<AnalysisLanguage, PlanStrings> = { en, ko, ja, zh, fr, ru };

export function planStrings(language: AnalysisLanguage): PlanStrings {
  return STRINGS[language] ?? en;
}
