/**
 * Fixed labels for the teardown report, mirroring `planStrings.ts`.
 * The model writes the analysis in the chosen language; these are the scaffolding
 * headings around it.
 */
import type { AnalysisLanguage } from "@shared/languages";

export interface TeardownStrings {
  title: (concept: string) => string;
  generatedOn: string;
  analysisTarget: string;
  generatedBy: string;
  sections: {
    summary: string;
    principles: string;
    faultLines: string;
    leapfrog: string;
    divergence: string;
    plan: string;
    openSource: string;
  };
  notes: {
    principles: string;
    faultLines: string;
  };
  table: {
    item: string;
    value: string;
    originalProduct: string;
    category: string;
    extractedPrinciples: string;
    foundFaultLines: string;
    divergenceScore: string;
    analysedMaterial: string;
    regenerated: string;
    materialSummary: (pages: number, total: number, confirmed: number) => string;
  };
  labels: {
    mechanism: string;
    whyItWorks: string;
    evidence: string;
    notStated: string;
    type: string;
    severity: string;
    opportunity: string;
    concept: string;
    architectureShift: string;
    coreFeatures: string;
    addressesFaultLine: string;
    originalApproach: string;
    ourApproach: string;
    unspecified: string;
    moat: string;
    divergenceScoreLine: (score: number, verdict: string) => string;
    followedOriginal: string;
    risk: string;
    fixDirection: string;
    legalChecks: string;
    techStack: string;
    area: string;
    technology: string;
    difficulty: string;
    phases: string;
    risks: string;
    mitigation: string;
    referenceModels: string;
    downloads: string;
    language: string;
    license: string;
    noDescription: string;
  };
  verdicts: {
    independent: string;
    acceptable: string;
    derivative: string;
  };
  empty: {
    thesis: string;
    principles: string;
    faultLines: string;
    architectureShift: string;
    features: string;
    moat: string;
    overlaps: string;
    stack: string;
    repos: string;
    defaultLegalNotes: string;
  };
  disclaimer: string;
  footer: string;
}

const en: TeardownStrings = {
  title: (c) => `Teardown-Based Product Design: ${c}`,
  generatedOn: "Generated",
  analysisTarget: "Subject",
  generatedBy: "Automatically generated by BuildPlanner in teardown mode.",
  sections: {
    summary: "Summary",
    principles: "Original Analysis — Operating Principles",
    faultLines: "Fault Lines — Trade-offs the Original Accepted",
    leapfrog: "Leapfrog Design — The New Product",
    divergence: "Divergence Audit",
    plan: "Implementation Plan",
    openSource: "Usable Open Source",
  },
  notes: {
    principles:
      "Not a feature list — a breakdown of the mechanisms that make this product work.",
    faultLines:
      "This is where the leap starts. You beat the original not by building it better, but by removing a constraint it could not avoid.",
  },
  table: {
    item: "Item",
    value: "Value",
    originalProduct: "Original product",
    category: "Category",
    extractedPrinciples: "Principles extracted",
    foundFaultLines: "Fault lines found",
    divergenceScore: "Divergence score",
    analysedMaterial: "Material analysed",
    regenerated: "redesigned once",
    materialSummary: (pages, total, confirmed) =>
      `${pages} official pages, ${total} user comments (${confirmed} confirmed relevant)`,
  },
  labels: {
    mechanism: "Mechanism",
    whyItWorks: "Why it works",
    evidence: "Evidence",
    notStated: "not stated",
    type: "Type",
    severity: "Severity",
    opportunity: "Opportunity",
    concept: "Concept",
    architectureShift: "Architectural shift",
    coreFeatures: "Core features",
    addressesFaultLine: "Fault line addressed",
    originalApproach: "Original approach",
    ourApproach: "Our approach",
    unspecified: "unspecified",
    moat: "Defensibility",
    divergenceScoreLine: (score, verdict) => `Divergence score: ${score}/100 — ${verdict}`,
    followedOriginal: "Where it follows the original",
    risk: "Risk",
    fixDirection: "How to fix",
    legalChecks: "Legal checks",
    techStack: "Tech stack",
    area: "Area",
    technology: "Technology",
    difficulty: "Implementation difficulty",
    phases: "Development phases",
    risks: "Risks",
    mitigation: "Mitigation",
    referenceModels: "Reference AI models",
    downloads: "downloads",
    language: "Language",
    license: "License",
    noDescription: "No description",
  },
  verdicts: {
    independent: "✅ Judged an independent design.",
    acceptable: "🟡 Independent enough, but review the items below before building.",
    derivative:
      "🔴 Too dependent on the original. Fix the items below before starting development.",
  },
  empty: {
    thesis: "_No thesis was produced._",
    principles:
      "_No operating principles were extracted. Check that the official URL is correct._",
    faultLines: "_No fault lines were found._",
    architectureShift: "_No architectural shift was stated._",
    features: "_No core features were designed._",
    moat: "_No defensibility was stated._",
    overlaps: "_None found._",
    stack: "_No tech stack was produced._",
    repos: "_No related open source was found._",
    defaultLegalNotes:
      "- Ideas and feature concepts are not copyrightable, but source code, UI assets and trademarks are.\n- Check the original's patent filings before starting development.",
  },
  disclaimer:
    "⚖️ This document is an analysis based only on publicly available information. It is not legal advice — have a professional review it before shipping.",
  footer:
    "Generated automatically by BuildPlanner in teardown mode. It is based on public information, so verify it further before building.",
};

const ko: TeardownStrings = {
  title: (c) => `역설계 기반 신규 앱 설계서: ${c}`,
  generatedOn: "생성일",
  analysisTarget: "분석 대상",
  generatedBy: "BuildPlanner 역설계 모드로 자동 생성되었습니다.",
  sections: {
    summary: "요약",
    principles: "원본 분석 — 작동 원리",
    faultLines: "개선 가능성 — 원본이 감수한 타협",
    leapfrog: "도약 설계 — 새 제품",
    divergence: "차별화 감사",
    plan: "구현 계획",
    openSource: "활용 가능한 오픈소스",
  },
  notes: {
    principles: "기능 목록이 아니라, 이 제품이 왜 작동하는지에 대한 메커니즘 분해입니다.",
    faultLines:
      "도약의 출발점입니다. 원본을 이기는 방법은 더 잘 만드는 것이 아니라, 원본이 피할 수 없었던 제약을 없애는 것입니다.",
  },
  table: {
    item: "항목",
    value: "값",
    originalProduct: "원본 제품",
    category: "제품 카테고리",
    extractedPrinciples: "추출된 작동 원리",
    foundFaultLines: "발견된 개선 지점",
    divergenceScore: "차별화 점수",
    analysedMaterial: "분석 자료",
    regenerated: "재설계 1회 수행",
    materialSummary: (pages, total, confirmed) =>
      `공식 페이지 ${pages}건, 사용자 발언 ${total}건 (제품 관련성 확인 ${confirmed}건)`,
  },
  labels: {
    mechanism: "메커니즘",
    whyItWorks: "작동 이유",
    evidence: "근거",
    notStated: "명시되지 않음",
    type: "유형",
    severity: "심각도",
    opportunity: "기회",
    concept: "개념",
    architectureShift: "구조적 전환",
    coreFeatures: "핵심 기능",
    addressesFaultLine: "해소하는 지점",
    originalApproach: "원본의 방식",
    ourApproach: "우리의 방식",
    unspecified: "미지정",
    moat: "방어 가능성",
    divergenceScoreLine: (score, verdict) => `차별화 점수: ${score}/100 — ${verdict}`,
    followedOriginal: "원본을 따라간 지점",
    risk: "위험",
    fixDirection: "수정 방향",
    legalChecks: "법적 확인 사항",
    techStack: "기술 스택",
    area: "영역",
    technology: "기술",
    difficulty: "구현 난이도",
    phases: "개발 단계",
    risks: "리스크",
    mitigation: "대응",
    referenceModels: "참고 AI 모델",
    downloads: "다운로드",
    language: "언어",
    license: "라이선스",
    noDescription: "설명 없음",
  },
  verdicts: {
    independent: "✅ 원본과 독립적인 설계로 판정되었습니다.",
    acceptable: "🟡 독립성은 확보했으나 아래 항목은 개발 전 재검토를 권합니다.",
    derivative: "🔴 원본 의존도가 높습니다. 아래 항목을 반드시 수정한 뒤 개발에 착수하세요.",
  },
  empty: {
    thesis: "_논지를 생성하지 못했습니다._",
    principles: "_작동 원리를 추출하지 못했습니다. 공식 URL이 정확한지 확인해주세요._",
    faultLines: "_개선 지점을 발견하지 못했습니다._",
    architectureShift: "_구조적 전환이 명시되지 않았습니다._",
    features: "_핵심 기능을 설계하지 못했습니다._",
    moat: "_방어 요소가 명시되지 않았습니다._",
    overlaps: "_발견되지 않았습니다._",
    stack: "_기술 스택을 생성하지 못했습니다._",
    repos: "_관련 오픈소스를 찾지 못했습니다._",
    defaultLegalNotes:
      "- 아이디어와 기능 개념은 저작권 보호 대상이 아니지만, 소스코드·UI 에셋·상표는 보호 대상입니다.\n- 원본의 특허 등록 여부를 개발 착수 전 확인하세요.",
  },
  disclaimer:
    "⚖️ 이 문서는 공개된 정보만을 근거로 작성된 분석입니다. 법률 자문이 아니며, 실제 제품화 전 전문가 검토를 권장합니다.",
  footer:
    "이 설계서는 BuildPlanner 역설계 모드로 자동 생성되었습니다. 공개 정보 기반 분석이므로 실제 개발 시 추가 검증이 필요합니다.",
};

const ja: TeardownStrings = {
  ...en,
  title: (c) => `リバースエンジニアリングによる新製品設計書: ${c}`,
  generatedOn: "作成日",
  analysisTarget: "分析対象",
  generatedBy: "BuildPlanner のリバースエンジニアリングモードで自動生成されました。",
  sections: {
    summary: "サマリー",
    principles: "原製品の分析 — 動作原理",
    faultLines: "改善余地 — 原製品が受け入れた妥協",
    leapfrog: "飛躍設計 — 新製品",
    divergence: "差別化監査",
    plan: "実装計画",
    openSource: "活用できるオープンソース",
  },
  notes: {
    principles: "機能一覧ではなく、この製品がなぜ機能するのかというメカニズムの分解です。",
    faultLines:
      "飛躍の出発点です。原製品に勝つ方法は、より良く作ることではなく、原製品が避けられなかった制約を取り除くことです。",
  },
  table: {
    ...en.table,
    item: "項目",
    value: "値",
    originalProduct: "原製品",
    category: "カテゴリ",
    extractedPrinciples: "抽出した動作原理",
    foundFaultLines: "発見した改善点",
    divergenceScore: "差別化スコア",
    analysedMaterial: "分析資料",
    regenerated: "再設計を1回実施",
    materialSummary: (pages, total, confirmed) =>
      `公式ページ ${pages}件、ユーザーの声 ${total}件（関連性確認済み ${confirmed}件）`,
  },
  labels: {
    ...en.labels,
    mechanism: "メカニズム",
    whyItWorks: "機能する理由",
    evidence: "根拠",
    notStated: "記載なし",
    type: "種別",
    severity: "深刻度",
    opportunity: "機会",
    concept: "コンセプト",
    architectureShift: "構造的転換",
    coreFeatures: "コア機能",
    addressesFaultLine: "解消する課題",
    originalApproach: "原製品の方式",
    ourApproach: "本製品の方式",
    unspecified: "未指定",
    moat: "防御可能性",
    divergenceScoreLine: (score, verdict) => `差別化スコア: ${score}/100 — ${verdict}`,
    followedOriginal: "原製品を踏襲した点",
    risk: "リスク",
    fixDirection: "修正の方向",
    legalChecks: "法的確認事項",
    techStack: "技術スタック",
    area: "領域",
    technology: "技術",
    difficulty: "実装難易度",
    phases: "開発フェーズ",
    risks: "リスク",
    mitigation: "対応",
    referenceModels: "参考 AI モデル",
    downloads: "ダウンロード",
    language: "言語",
    license: "ライセンス",
    noDescription: "説明なし",
  },
  verdicts: {
    independent: "✅ 原製品から独立した設計と判定されました。",
    acceptable: "🟡 独立性は確保されていますが、以下の項目は開発前に再検討してください。",
    derivative: "🔴 原製品への依存度が高いです。以下を修正してから開発に着手してください。",
  },
  disclaimer:
    "⚖️ 本書は公開情報のみに基づく分析です。法的助言ではないため、製品化の前に専門家の確認を受けてください。",
  footer:
    "本設計書は BuildPlanner のリバースエンジニアリングモードで自動生成されました。公開情報に基づくため、実開発前に追加検証が必要です。",
};

const zh: TeardownStrings = {
  ...en,
  title: (c) => `逆向工程新产品设计书: ${c}`,
  generatedOn: "生成日期",
  analysisTarget: "分析对象",
  generatedBy: "由 BuildPlanner 逆向工程模式自动生成。",
  sections: {
    summary: "摘要",
    principles: "原产品分析 — 运作原理",
    faultLines: "改进空间 — 原产品做出的妥协",
    leapfrog: "跨越式设计 — 新产品",
    divergence: "差异化审计",
    plan: "实施计划",
    openSource: "可用的开源项目",
  },
  notes: {
    principles: "这不是功能清单，而是对该产品为何能运作的机制拆解。",
    faultLines:
      "这是跨越的起点。战胜原产品的方法不是做得更好，而是消除它无法回避的约束。",
  },
  table: {
    ...en.table,
    item: "项目",
    value: "值",
    originalProduct: "原产品",
    category: "产品类别",
    extractedPrinciples: "提取的运作原理",
    foundFaultLines: "发现的改进点",
    divergenceScore: "差异化评分",
    analysedMaterial: "分析材料",
    regenerated: "已重新设计一次",
    materialSummary: (pages, total, confirmed) =>
      `官方页面 ${pages} 条，用户反馈 ${total} 条（确认相关 ${confirmed} 条）`,
  },
  labels: {
    ...en.labels,
    mechanism: "机制",
    whyItWorks: "有效原因",
    evidence: "依据",
    notStated: "未说明",
    type: "类型",
    severity: "严重度",
    opportunity: "机会",
    concept: "概念",
    architectureShift: "结构性转变",
    coreFeatures: "核心功能",
    addressesFaultLine: "所解决的问题",
    originalApproach: "原产品做法",
    ourApproach: "我们的做法",
    unspecified: "未指定",
    moat: "护城河",
    divergenceScoreLine: (score, verdict) => `差异化评分: ${score}/100 — ${verdict}`,
    followedOriginal: "沿袭原产品之处",
    risk: "风险",
    fixDirection: "修改方向",
    legalChecks: "法律确认事项",
    techStack: "技术栈",
    area: "领域",
    technology: "技术",
    difficulty: "实现难度",
    phases: "开发阶段",
    risks: "风险",
    mitigation: "应对",
    referenceModels: "参考 AI 模型",
    downloads: "下载量",
    language: "语言",
    license: "许可证",
    noDescription: "无描述",
  },
  verdicts: {
    independent: "✅ 判定为独立于原产品的设计。",
    acceptable: "🟡 已具备独立性，但以下项目建议在开发前复核。",
    derivative: "🔴 对原产品依赖度过高。请先修正以下项目再开始开发。",
  },
  disclaimer:
    "⚖️ 本文档仅基于公开信息分析，不构成法律意见。产品化前请咨询专业人士。",
  footer:
    "本设计书由 BuildPlanner 逆向工程模式自动生成。基于公开信息，实际开发前需进一步验证。",
};

const fr: TeardownStrings = {
  ...en,
  title: (c) => `Conception issue d'un teardown : ${c}`,
  generatedOn: "Généré le",
  analysisTarget: "Sujet analysé",
  generatedBy: "Généré automatiquement par BuildPlanner en mode teardown.",
  sections: {
    summary: "Résumé",
    principles: "Analyse de l'original — principes de fonctionnement",
    faultLines: "Marges d'amélioration — compromis acceptés par l'original",
    leapfrog: "Conception de rupture — le nouveau produit",
    divergence: "Audit de différenciation",
    plan: "Plan de mise en œuvre",
    openSource: "Open source réutilisable",
  },
  notes: {
    principles:
      "Ce n'est pas une liste de fonctionnalités, mais une décomposition des mécanismes qui font fonctionner ce produit.",
    faultLines:
      "C'est le point de départ du saut. On ne bat pas l'original en le faisant mieux, mais en supprimant une contrainte qu'il ne pouvait pas éviter.",
  },
  table: {
    ...en.table,
    item: "Élément",
    value: "Valeur",
    originalProduct: "Produit d'origine",
    category: "Catégorie",
    extractedPrinciples: "Principes extraits",
    foundFaultLines: "Points d'amélioration trouvés",
    divergenceScore: "Score de différenciation",
    analysedMaterial: "Matériel analysé",
    regenerated: "reconçu une fois",
    materialSummary: (pages, total, confirmed) =>
      `${pages} pages officielles, ${total} retours d'utilisateurs (${confirmed} confirmés pertinents)`,
  },
  labels: {
    ...en.labels,
    mechanism: "Mécanisme",
    whyItWorks: "Pourquoi ça fonctionne",
    evidence: "Preuve",
    notStated: "non précisé",
    type: "Type",
    severity: "Gravité",
    opportunity: "Opportunité",
    concept: "Concept",
    architectureShift: "Basculement architectural",
    coreFeatures: "Fonctionnalités clés",
    addressesFaultLine: "Point traité",
    originalApproach: "Approche de l'original",
    ourApproach: "Notre approche",
    unspecified: "non spécifié",
    moat: "Défendabilité",
    divergenceScoreLine: (score, verdict) => `Score de différenciation : ${score}/100 — ${verdict}`,
    followedOriginal: "Points repris de l'original",
    risk: "Risque",
    fixDirection: "Correction",
    legalChecks: "Vérifications juridiques",
    techStack: "Stack technique",
    area: "Domaine",
    technology: "Technologie",
    difficulty: "Difficulté de mise en œuvre",
    phases: "Phases de développement",
    risks: "Risques",
    mitigation: "Atténuation",
    referenceModels: "Modèles d'IA de référence",
    downloads: "téléchargements",
    language: "Langage",
    license: "Licence",
    noDescription: "Aucune description",
  },
  verdicts: {
    independent: "✅ Conception jugée indépendante de l'original.",
    acceptable: "🟡 Indépendance acquise, mais revoyez les points ci-dessous avant de développer.",
    derivative:
      "🔴 Dépendance trop forte à l'original. Corrigez les points ci-dessous avant de démarrer.",
  },
  disclaimer:
    "⚖️ Ce document est une analyse fondée uniquement sur des informations publiques. Ce n'est pas un avis juridique — faites-le relire par un professionnel avant commercialisation.",
  footer:
    "Généré automatiquement par BuildPlanner en mode teardown. L'analyse repose sur des informations publiques ; vérifiez-la avant de développer.",
};

const ru: TeardownStrings = {
  ...en,
  title: (c) => `Проект нового продукта на основе разбора: ${c}`,
  generatedOn: "Создано",
  analysisTarget: "Объект анализа",
  generatedBy: "Автоматически создано BuildPlanner в режиме разбора.",
  sections: {
    summary: "Сводка",
    principles: "Анализ оригинала — принципы работы",
    faultLines: "Возможности улучшения — компромиссы оригинала",
    leapfrog: "Прорывной проект — новый продукт",
    divergence: "Аудит отличий",
    plan: "План реализации",
    openSource: "Подходящий open source",
  },
  notes: {
    principles:
      "Это не список функций, а разбор механизмов, благодаря которым продукт работает.",
    faultLines:
      "Отсюда начинается рывок. Оригинал побеждают не тем, что делают лучше, а снятием ограничения, которого он не мог избежать.",
  },
  table: {
    ...en.table,
    item: "Пункт",
    value: "Значение",
    originalProduct: "Исходный продукт",
    category: "Категория",
    extractedPrinciples: "Извлечено принципов",
    foundFaultLines: "Найдено точек улучшения",
    divergenceScore: "Оценка отличия",
    analysedMaterial: "Проанализированный материал",
    regenerated: "выполнен один пересмотр",
    materialSummary: (pages, total, confirmed) =>
      `официальных страниц: ${pages}, отзывов пользователей: ${total} (подтверждено релевантных: ${confirmed})`,
  },
  labels: {
    ...en.labels,
    mechanism: "Механизм",
    whyItWorks: "Почему это работает",
    evidence: "Обоснование",
    notStated: "не указано",
    type: "Тип",
    severity: "Критичность",
    opportunity: "Возможность",
    concept: "Концепция",
    architectureShift: "Архитектурный сдвиг",
    coreFeatures: "Ключевые возможности",
    addressesFaultLine: "Какую проблему снимает",
    originalApproach: "Подход оригинала",
    ourApproach: "Наш подход",
    unspecified: "не задано",
    moat: "Защищённость",
    divergenceScoreLine: (score, verdict) => `Оценка отличия: ${score}/100 — ${verdict}`,
    followedOriginal: "Где повторяется оригинал",
    risk: "Риск",
    fixDirection: "Как исправить",
    legalChecks: "Юридические проверки",
    techStack: "Технологический стек",
    area: "Область",
    technology: "Технология",
    difficulty: "Сложность реализации",
    phases: "Этапы разработки",
    risks: "Риски",
    mitigation: "Меры",
    referenceModels: "Опорные модели ИИ",
    downloads: "загрузок",
    language: "Язык",
    license: "Лицензия",
    noDescription: "Нет описания",
  },
  verdicts: {
    independent: "✅ Признано самостоятельным решением.",
    acceptable: "🟡 Самостоятельность достигнута, но пункты ниже стоит пересмотреть до разработки.",
    derivative:
      "🔴 Слишком сильная зависимость от оригинала. Исправьте пункты ниже до начала разработки.",
  },
  disclaimer:
    "⚖️ Документ основан только на публичной информации и не является юридической консультацией — до выпуска продукта покажите его специалисту.",
  footer:
    "Создано BuildPlanner в режиме разбора. Анализ опирается на публичные данные, поэтому перед разработкой нужна дополнительная проверка.",
};

const STRINGS: Record<AnalysisLanguage, TeardownStrings> = { en, ko, ja, zh, fr, ru };

export function teardownStrings(language: AnalysisLanguage): TeardownStrings {
  return STRINGS[language] ?? en;
}
